---
name: tmate

instance_groups:
  - name: master
    azs:  [z1]

    stemcell: default
    vm_type: default
    networks:
      - name: default

    instances: 1
    jobs:
      - name:    tmate
        release: tmate
        properties:
          host: ((public_hostname_or_ip))


stemcells:
- alias:   default
  os:      ubuntu-xenial
  version: latest

update:
  canaries: 1
  canary_watch_time: 1000-120000
  max_in_flight: 50
  serial: false
  update_watch_time: 1000-120000

variables:
  - name: public_hostname_or_ip

releases:
- name:    tmate
  version: 1.0.2
  url:     https://github.com/cloudfoundry-community/tmate-boshrelease/releases/download/v1.0.2/tmate-1.0.2.tgz
  sha1:    30e3469003c2326ed818b410ceaea26c7443ee9b
