---
name: tmate

instance_groups:
  - name: master
    azs:  [z1]

    stemcell: default
    vm_type: default
    networks:
      - name: default

    instances: 1
    jobs:
      - name:    tmate
        release: tmate
        properties:
          host: ((public_hostname_or_ip))


stemcells:
- alias:   default
  os:      ubuntu-xenial
  version: latest

update:
  canaries: 1
  canary_watch_time: 1000-120000
  max_in_flight: 50
  serial: false
  update_watch_time: 1000-120000

variables:
  - name: public_hostname_or_ip

releases:
- name:    tmate
  version: 1.0.1
  url:     https://github.com/cloudfoundry-community/tmate-boshrelease/releases/download/v1.0.1/tmate-1.0.1.tgz
  sha1:    b7a3696e42334c8107e816285e49aa36b6cd8520
